### ISSUE TITLE
Does not work with blobs as sql params

### ISSUE THREAD

**Issue by Burtan** [dellisd/sqldelight-sqlite-wasm#2]
Hi,
I know this project does not use blobs, but I tried the web worker and it seems blobs (e.g. as ArrayBuffer) are not supported by the bind parameter.
```
      return postMessage({
        id: data.id,
        results: { values: db.exec({ sql: data.sql, bind: data.params, returnValue: "resultRows" }) },
      })

WebWorkerException: {"message":"Unsupported bind() argument type: object","name":"Error"}
```

Do you know if this is a limitation of sqlite3.wasm or the api? I guess we cannot do much about it?
I could theoretically store base64 encoded data instead of blobs.

**Comment by Burtan** [comment]
It seems that ByteArray data from kotlin is translated to Array of number in the web worker instead of Int8Array which should be the ByteArray representation in js? Actual binary data types in js are supported by sqlite wasm.

Maybe it happens [here](https://github.com/cashapp/sqldelight/blob/9f86d04fed4794768d598264f2bc3a8f4d38e6f6/drivers/web-worker-driver/src/main/kotlin/app/cash/sqldelight/driver/worker/WebWorkerDriver.kt#L189)?

**Comment by dellisd** [comment]
Indeed, this seems to be bug in the SQLDelight driver! I removed the `toTypedArray()` in the driver and it worked for me locally.

Feel free to open a PR on SQLDelight with the fix, or if not then I'll get around to it later in the weekend.

**Comment by Burtan** [comment]
I created a PR 
https://github.com/cashapp/sqldelight/pull/3978
